//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dogily_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ProDeID { get; set; }
        public Nullable<byte> RemainAmount { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Description { get; set; }
        public string Ingredients { get; set; }
        public string IDPro { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> Weight { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Product Product { get; set; }
        public virtual Weight Weight1 { get; set; }
    }
}
